export default [
    { key: 'ua', value: 'Українська' },
    { key: 'ru', value: 'Русский' },
    { key: 'by', value: 'Беларуская' },
    { key: 'ge', value: 'ქართული' },
    { key: 'cn', value: '中文' },
    { key: 'in', value: 'हिन्दी' },
    { key: 'en', value: 'English' },
    { key: 'es', value: 'Español' },
    { key: 'jp', value: '日本語' },
    { key: 'gr', value: 'Ελληνικά' },
    { key: 'it', value: 'Italiano' },
    { key: 'pt', value: 'Português' },
    { key: 'se', value: 'Svenska' },
    { key: 'dk', value: 'Dansk' },
    { key: 'hu', value: 'Magyar' },
    { key: 'kz', value: 'Қазақ' },
    { key: 'pl', value: 'Polski' },
    { key: 'cz', value: 'Čeština' },
    { key: 'lv', value: 'Latviešu' },
    { key: 'lt', value: 'Lietuvių' },
    { key: 'ee', value: 'Eesti' },
    { key: 'am', value: 'Հայերեն' },
    { key: 'az', value: 'Azərbaycan dili' },
    { key: 'fr', value: 'Français' },
    { key: 'nl', value: 'Nederlands' },
    { key: 'de', value: 'Deutsch' },
];
// export default [
//   'Azərbaycan dili',
//   'Bahasa Indonesia',
//   'Bosanski',
//   'Dansk',
//   'Deutsch',
//   'Eesti',
//   'English',
//   'Español',
//   'Esperanto',
//   'Français',
//   'Hrvatski',
//   'Italiano',
//   'Karjalan kieli',
//   'Kiswahili',
//   'Latviešu',
//   'Lietuvių',
//   'Lingua Latina',
//   'Magyar',
//   'Mirandés',
//   'Moldovenească',
//   'Italiano',
//   'Karjalan kieli',
//   'Italiano',
//   'Karjalan kieli',
//   'Kiswahili',
//   'Latviešu',
//   'Lietuvių',
//   'Lingua Latina',
//   'Magyar',
//   'Mirandés',
//   'Moldovenească',
//   'Nederlands',
//   'Norsk',
//   'O‘zbek',
//   'Polski',
//   'Português',
//   'Português brasileiro',
//   'Română',
//   'Shqip',
//   'Slovenščina',
//   'Suomi',
//   'Svenska',
//   'Tagalog',
//   'Taqbaylit',
//   'Tiếng Việt',
//   'Tolışə zıvon',
//   'Türkmen',
//   'Türkçe',
//   'Čeština',
//   'Ελληνικά',
//   'Slovenčina',
//   'Адыгабзэ',
//   'Башҡортса',
//   'Беларуская',
//   'Буряад',
//   'Български',
//   'Ирон',
//   'Коми кыв',
//   'Кыргыз тили',
//   'Къумукъ тил',
//   'Лезги чІал',
//   'Марий йылме',
//   'Монгол',
//   'Русинськый',
//   'Русский',
//   'Татарча',
//   'Саха тыла',
//   'Тоҷикӣ',
//   'Тыва дыл',
//   'Српски',
//   'Чăвашла',
//   'Эрзянь кель',
//   'Хальмг келн',
//   'Удмурт',
//   'Українська',
//   'Қазақша',
//   'नेपाली',
//   'हिन्दी',
//   'বাংলা',
//   'ಕನ್ನಡ',
//   'සිංහල',
//   'ภาษาไทย',
//   'ქართული',
//   'ဗမာစာ',
//   '日本語',
//   '汉语',
//   '臺灣話',
//   '한국어',
//   'Հայերեն',
//   'עברית',
//   'اردو',
//   'العربية',
//   'فارسی',
//   'پنجابی',
// ];
